### ISSUE TITLE
How to change style of first element after element is opened?

### ISSUE THREAD

**Issue by AleksandarMiha** [BrightspaceUI/dropdown#164] opened 2019-08-07 09:57 UTC
How to style the first element which is opened? I inspect an element and I need to change element with tag <d2l-menu-item-return>. I need to change the background and remove the border top and bottom? Please help?

    z-index: 2; */
    background-color: var(--d2l-color-celestine-plus-2);
    border-top: 1px solid var(--d2l-color-celestine-plus-1);
    border-bottom: 1px solid var(--d2l-color-celestine-plus-1);
    color: var(--d2l-color-celestine)

Example: 
https://imge.to/i/AIPGG

**Comment by dlockhart** [comment] 2019-08-07 13:53
Hi @AleksandarMiha. This dropdown component adheres to the style guide for our company's product -- Brightspace. The style it isn't configurable, by design.

You're still more than welcome to use it, but we won't be adding any style configuration options at this time. Feel free to fork it though and add those configuration options yourself!

**Closed by dlockhart** 2019-08-07 13:53 UTC

**Comment by AleksandarMiha** [comment] 2019-08-07 19:47
@dlockhart  How to target this element and set custom my css???
